* <<<S1>>> Engineering Physics
:properties:
:author:  Physics Department
:date: 
:end:

#+startup: showall
#+begin_comment
NIL
#+end_comment


{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** COURSE OBJECTIVES
- Provide an overview of the characteristics of sound; production and applications of ultrasound.
- Develop an understanding of quantum mechanical concepts and their theories.
- Explain the theories of physics of semiconductors.
- Describe the principle of laser action and their production.
- Analyse the propagation of light through optical fibres and losses in fibre optic communication.

{{{unit}}}
|UNIT I|ACOUSTICS AND ULTRASONICS |9| 
Acoustics: Classification- Music & Noise - Characteristics of Sound Pitch/Frequency, Loudness/Intensity- decibel scale - Weber–Fechner law – Loudness Curves- Quality/Timbre 
Ultrasonics: Production - Magnetostriction and Piezoelectric methods - Acoustic grating – Non Destructive Testing – pulse echo system -reflection and transmission modes –Modes of data presentation- A, B and C scan displays – Sonogram. 

{{{unit}}}
|UNIT II|QUANTUM PHYSICS |9| 
Planck’s theory (derivation) – Deduction of Wien’s displacement law and Rayleigh-Jeans law from Planck’s theory – Properties of Matter waves - wave particle duality - Schrödinger’s wave equation – Time independent and time dependent equations – Physical significance of wave function – Particle in a one dimensional box  and extension to three dimensional box – Degeneracy of electron energy states – Quantum free electron theory – Density of states –  Fermi-Dirac statistics– Free electron concentration in metals.

{{{unit}}}
|UNIT III|SEMICONDUCTING MATERIALS |9| 
Classification of semiconductors based on doping and band gap – Intrinsic semiconductor – Concept of hole – carrier concentration derivation –Fermi level and its variation with temperature – electrical conductivity – band gap determination – Extrinsic semiconductors – Carrier concentration derivation in n-type and p-type semiconductors – Variation of Fermi level with temperature and impurity concentration

{{{unit}}}
|UNIT IV|PHOTONICS|8| 
Interaction of Radiation with Matter-Spontaneous and stimulated emissions– Einstein’s A and B coefficients – Conditions for Laser action -Population inversion - Active medium -– pumping schemes – Optical resonant cavity- Light Amplification-Types of lasers – Nd: YAG, CO2  and Semiconductor lasers- homo junction & hetero junction laser.

{{{unit}}}
|UNIT V|FIBRE OPTICS|9| 
Principle and propagation of light in optical fibres –Numerical aperture and Acceptance angle,  Types of optical fibres (material, mode & refractive index) – Losses in fibres - attenuation, dispersion - Fibre Optical Communication system (Block diagram) - Active and passive sensors –  pressure and displacement.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Describe the characteristics of sound and Ultrasonics production and applications. 
- Explain the basic quantum mechanical concepts and their applications .
- Analyze the  Physics of all types of semiconductors .
- Elucidate the principle and working of different type of lasers .
- Explicate the principle, propagation and losses in  fibre optic communication.

** TEXT BOOKS
1. M.Arumugam,.A.Rajalakshmi., Engineering Physics, Anuradha Publications,2019
2. Salivahanan, S., Rajalakshmi, A., Karthie, S., Rajesh, N.P., Physics for Electronics Engineering and Information Science, McGraw Hill Education (India) Private Limited,2018 in reference books.    
3. Gaur R.K. and Gupta S.L. Engineering Physics. Dhanpat Rai publishers, 2012
4.  A text book of Engineering Physics, M. N. Avadhanulu, P. G. Shirsagar, S. Chand & Co. Ltd. 2012 Ninth Revised Edition .

** REFERENCES
1.   Halliday, D., Resnick, R. & Walker, J. ― Principles of Physics. Wiley, 2015.
2.  Serway, R.A. & Jewett, J.W. ― Physics for Scientists and Engineers. Cengage Learning, 2010. 
3.  Tipler, P.A. & Mosca, G. ― Physics for Scientists and Engineers with Modern Physics’. W.H.Freeman, 2007.
