 <<<S2>>> Foundations of Data Science 
:properties:
:author: Dr. T. T. Mirnalinee and Ms. S. Rajalakshmi
:date: 
:end:

#+startup: showall

#+begin_comment
- We checked other university courses relevant to this
- Should we include Probabilty and statistics.

Randomness -- Empirical Distributions -- Testing Hypothesis -- Estimation --
Why the mean matters -- Prediction -- Inference for Regression.

Book 1: (Ch 2)-Unit I , Ch(3,4,5) -Unit II
Book 2 :(Ch 9,10) - unit II
#+end_comment

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn fundamentals of Data Science using Python
  # for carrying out basic statistical modeling and analysis
- To understand probability distributions and statistical Inferences
  # used for statistical modeling
- To be familar with supervised and unsupervised methods in machine
  learning
- To explore the algorithms used for analysing massive data problems
  and social networks
- To learn about visualization. 

{{{unit}}}
|UNIT I | INTRODUCTION TO DATA SCIENCE | 9 |
Introduction: Need for data science -- Benefits and uses -- Facets of
data -- Big data ecosystem -- The data science process: Retrieving
data -- Cleansing, integrating and transforming data -- Data analysis
-- Build the models -- Presenting findings and building applications.

{{{unit}}}
|UNIT II | TOOLBOXES FOR DATA SCIENTISTS| 10 |
Introduction to Python; Fundamental Python Libraries for Data
Scientists : Numpy -- Scipy -- ScikitLearn -- Pandas -- Matplotlib;
IDE; Data Manipulation with Python

{{{unit}}}
|UNIT III | DESCRIPTIVE STATISTICS | 8 |
Introduction -- Data Preparation -- Exploratory Data Analysis: Data
summarization -- Data distribution -- Outlier Treatment -- Measuring
asymmetry -- Continuous distribution; Estimation: Mean -- Variance --
Sampling -- Covariance -- Correlation.

{{{unit}}}
|UNIT IV | STATISTICAL INFERENCE | 8 |
Introduction -- Frequentist Approach -- Measuring the Variability in
Estimates: Point estimates -- Confidence intervals; Hypothesis
Testing: Using confidence intervals -- Using p-values.

{{{unit}}}
|UNIT V | MACHINE LEARNING | 10 |
Supervised Learning: Introduction -- kNN classifier; Regression
analysis: Linear regression -- Logistic regression; Unsupervised
Learning : Introduction -- Clustering; Evaluation metrics.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Develop Python programs to perform analysis on data (K3)
- Understand various probability distributions and statistical
  inferences (K2)
- Develop applications to demonstrate machine learning algorithms in
  practice (K3)
- Understand the principles of handling data streams (K2)
- Discuss topic and graphical modeling techniques in real world
  problem (K2).
 
** TEXT BOOKS
1. Davy Cielen, Arno D B Meysman, Mohamed Ali, ``Introducing Data
   Science -- Big data, Machine Learning, and more using Python
   tools'', Manning Publications Co, 2016. (Unit I)
2. Laura Igual, Santi Segua­, ``Introduction to Data Science -- A
   Python Approach to Concepts, Techniques and Applications'',
   Springer Nature, 2017 (Unit I, II, III, IV, V)
3. Foster Provost and Tom Fawcett, ``Data Science for Business'',
   O'Reilly Media, 2013
4. Jake VanderPlas, ``Python Data Science Handbook: Essential Tools
   for Working with Data '', O'Reilly Media, 2016
5. Rachel Schutt, Cathy O'Neil, ``Doing Data Science'', O'Reilly
   Media, 2016
